/**
 * Kendo UI v2024.2.514 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.html.base.js";import"./kendo.icons.js";var __meta__={id:"html.chip",name:"Html.Chip",category:"web",description:"HTML rendering utility for Kendo UI for jQuery.",depends:["html.base","icons"],features:[]};!function(a,e){var s=window.kendo,t=s.html.HTMLBase,n=t.extend({init:function(a,e){t.fn.init.call(this,a,e),this._wrapper()},options:{name:"HTMLChip",size:"medium",rounded:"medium",fillMode:"solid",themeColor:"base",attr:{},icon:"",iconClass:"",iconAttr:{},removable:!1,removableAttr:{},removeIcon:"x-circle",removeIconClass:"",content:"",text:"",actions:[],stylingOptions:["size","rounded","fillMode","themeColor"]},_wrapper:function(){var e=this,t=e.options;t.text=t.text||t.label,e.wrapper=e.element.wrap("<div class='k-chip'></div>").parent().attr(t.attr),e._addClasses(),t.icon?e.wrapper.prepend(a(s.ui.icon({icon:t.icon,size:"small",iconClass:"k-chip-icon"+(t.iconClass?` ${t.iconClass}`:"")})).attr(t.iconAttr)):t.iconClass?e.wrapper.prepend(a("<span class='"+t.iconClass+"'></span>").attr(t.iconAttr)):t.avatarClass&&e.wrapper.prepend(a("<span class='k-chip-avatar k-avatar k-avatar-md k-avatar-solid k-avatar-solid-primary k-rounded-full "+t.avatarClass+"'></span>").attr(t.iconAttr)),e.element.addClass("k-chip-content"),t.text&&e.element.html('<span class="k-chip-label">'+t.text+"</span>"),!1===t.visible&&e.wrapper.addClass("k-hidden"),!0===t.selected&&e.wrapper.addClass("k-selected"),!1===t.enabled&&e.wrapper.addClass("k-disabled"),(t.actions&&t.actions.length>0||t.removable)&&e._actions()},_actions:function(){var e=this,t=e.options;if(e.actionsWrapper=a("<span class='k-chip-actions'></span>"),e.actionsWrapper.appendTo(e.wrapper),t.actions&&t.actions.length>0)for(var n=0;n<t.actions.length;n++){var i=t.actions[n];e.actionsWrapper.append(a(`<span class='k-chip-action ${i.iconClass?i.iconClass:""}'>${s.ui.icon({icon:i.icon,size:"small"})}</span>`).attr(i.attr?i.attr:{}))}t.removable&&e.actionsWrapper.append(a(`<span class='k-chip-action k-chip-remove-action'>${s.ui.icon({icon:t.removeIcon,size:"small"})}</span>`).attr(t.removableAttr))}});a.extend(s.html,{renderChip:function(e,s){return e&&!a.isPlainObject(e)||(s=e,e=a("<span></span>")),new n(e,s).html()},HTMLChip:n}),s.cssProperties.registerPrefix("HTMLChip","k-chip-"),s.cssProperties.registerValues("HTMLChip",[{prop:"rounded",values:s.cssProperties.roundedValues.concat([["full","full"]])}])}(window.kendo.jQuery);var kendo$1=kendo;export{kendo$1 as default};
//# sourceMappingURL=kendo.html.chip.js.map
